// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Editora } from '../editora';
import { Livro } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';


@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrl: './livro-lista.component.css'
})
export class LivroListaComponent implements OnInit{
  public editoras: Array<Editora> = [];
  public livros: Array<Livro> = [];

  constructor(
    private servEditora: ControleEditoraService, 
    private servLivros: ControleLivrosService
  ) {}

  async ngOnInit(): Promise<void> {
    this.editoras = this.servEditora.getEditoras();
    await this.servLivros.obterLivros().then((livros: Livro[]) => {
      this.livros = livros;
    });
  }

  excluir = (codigo: String): void => {
    this.servLivros.excluir(codigo).then(() => {
      this.servLivros.obterLivros().then((livros: Livro[]) => {
        this.livros = livros;
      })
    });
  }

  obterNome = (codEditora: number): string => {
    return this.servEditora.getNomeEditora(codEditora);
  }
  
}

<main class="container">
    <h1>Catálogo de Livros</h1>

    <table class="table table-striped table-hover">
        <thead class="table-dark">
            <tr>
                <th>Título</th>
                <th>Resumo</th>
                <th>Editora</th>
                <th>Autores</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let livro of livros">
                <td class="d-flex flex-column align-items-start">
                    {{ livro.titulo }}
                    <button class="btn btn-danger" (click)="excluir(livro.codigo)">Excluir</button>
                </td>

                <td>{{ livro.resumo }}</td>

                <td>{{ obterNome(livro.codEditora) }}</td>

                <td>
                    <ul>
                        <li *ngFor="let autor of livro.autores">
                            {{ autor }}
                        </li>
                    </ul>
                </td>
            </tr>
        </tbody>
    </table>
</main>

// clientes/livros-react/src/LivroLista.js
import ControleLivros from "./controle/ControleLivros";
import ControleEditora from "./controle/ControleEditora";
import { useState, useEffect } from "react";


const controleLivro = new ControleLivros();

const controleEditora = new ControleEditora();

function LinhaLivro(props) {
    let nomeEditora = controleEditora.getNomeEditora(props.livro.codEditora);

    return (
        <>
            <tr>
                <td className="d-flex flex-column align-items-start">{props.livro.titulo}<button className="btn btn-danger" onClick={() => props.excluir(props.livro._id)}>Excluir</button></td>
                <td>{props.livro.resumo}</td>
                <td>{nomeEditora}</td>
                <td><ul>{props.livro.autores.map((autor, index) => <li key={index}>{autor}</li>)}</ul></td>
            </tr>
        </>
    )
}

const LivroLista = () => {
    const [livros, setLivros] = useState([]);
    const [carregado, setCarregado] = useState(false);

    useEffect(() => {
        const fetchLivros = async () => {
            await controleLivro.obterLivros().then((livrosObtidos) => {
                setLivros(livrosObtidos);
                setCarregado(true);
            });
        };

        if (!carregado) {
          fetchLivros();
        }
      }, [carregado]);
    
    const excluir = async (codigo) => {
        await controleLivro.excluir(codigo)
        setCarregado(false); 
    };

    return (
        <>
            <main className="container">
                <h1>Catálogo de Livros</h1>
                <table className="table table-striped table-hover">
                    <thead className="table-dark">
                        <tr>
                            <th>Título</th>
                            <th>Resumo</th>
                            <th>Editora</th>
                            <th>Autores</th>
                        </tr>
                    </thead>
                    <tbody>
                        {livros.map((livro, index) => (
                            <LinhaLivro 
                                key={index}
                                livro={livro}
                                excluir={excluir}
                            />
                        ))}
                    </tbody>
                </table>
            </main>
        </>
    )
}

export default LivroLista;
