// clientes/livros-next/pages/LivroLista.tsx
import type { NextPage } from 'next';
import React, { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css';
import Livro from '@/classes/modelo/Livro';
import Head from 'next/head';
import { Menu } from '@/componentes/Menu';
import { LinhaLivro } from '@/componentes/LinhaLivro';
import ControleLivros from '@/classes/controle/ControleLivros';


const controleLivros = new ControleLivros();

const LivroLista: NextPage = () => {
    const [livros, setLivros] = useState<Array<Livro>>([]);
    const [carregado, setCarregado] = useState<boolean>(false);

    useEffect(() => {
        const fetchLivros = async () => {
            await controleLivros.obterLivros().then((livrosObtidos) => {
                setLivros(livrosObtidos);
                setCarregado(true);
            });
        }

        if (!carregado) {
            fetchLivros();
        }
    }, [carregado]);

    const excluir = (codigo: String) => {
        controleLivros.excluir(codigo).then(() => {
            setCarregado(false);
        });
    }

    return (
        <>
        <div className={styles.container}>
            <Head>
                <title>Catálogo de Livros</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Menu />
            <main className="container">
                <h1>Catálogo de Livros</h1>
                <table className="table table-striped table-hover">
                    <thead className="table-dark">
                        <tr>
                            <th>Título</th>
                            <th>Resumo</th>
                            <th>Editora</th>
                            <th>Autores</th>
                        </tr>
                    </thead>
                    <tbody>
                        {livros.map((livro, index) => (
                            <LinhaLivro 
                                key={index}
                                livro={livro}
                                excluir={ () => excluir(`${livro.codigo}`) }
                            />
                        ))}
                    </tbody>
                </table>
            </main>
        </div>
        </>
    ) 
}

export default LivroLista;

// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Editora } from '../editora';
import { Livro } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';


@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrl: './livro-lista.component.css'
})
export class LivroListaComponent implements OnInit{
  public editoras: Array<Editora> = [];
  public livros: Array<Livro> = [];

  constructor(
    private servEditora: ControleEditoraService, 
    private servLivros: ControleLivrosService
  ) {}

  async ngOnInit(): Promise<void> {
    this.editoras = this.servEditora.getEditoras();
    await this.servLivros.obterLivros().then((livros: Livro[]) => {
      this.livros = livros;
    });
  }

  excluir = (codigo: String): void => {
    this.servLivros.excluir(codigo).then(() => {
      this.servLivros.obterLivros().then((livros: Livro[]) => {
        this.livros = livros;
      })
    });
  }

  obterNome = (codEditora: number): string => {
    return this.servEditora.getNomeEditora(codEditora);
  }
  
}

<main class="container">
    <h1>Catálogo de Livros</h1>

    <table class="table table-striped table-hover">
        <thead class="table-dark">
            <tr>
                <th>Título</th>
                <th>Resumo</th>
                <th>Editora</th>
                <th>Autores</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let livro of livros">
                <td class="d-flex flex-column align-items-start">
                    {{ livro.titulo }}
                    <button class="btn btn-danger" (click)="excluir(livro.codigo)">Excluir</button>
                </td>

                <td>{{ livro.resumo }}</td>

                <td>{{ obterNome(livro.codEditora) }}</td>

                <td>
                    <ul>
                        <li *ngFor="let autor of livro.autores">
                            {{ autor }}
                        </li>
                    </ul>
                </td>
            </tr>
        </tbody>
    </table>
</main>
