// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';


@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrl: './livro-dados.component.css'
})
export class LivroDadosComponent implements OnInit{
  public livro: Livro = new Livro();
  public autoresForm: string = '';
  public editoras: Array<Editora> = [];
  

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = (): void => {
    this.livro.autores = this.autoresForm.split('\n');
    this.livro.codEditora = Number(this.livro.codEditora); // Converting codEditora from string to number format
    this.servLivros.incluir(this.livro).then(() => {
      this.router.navigateByUrl('/lista')
    });
  }

}

<main class="container">
    <h1>Dados do Livro</h1>

    <form (submit)="incluir()" ngNativeValidate>
        <div class="titulo mb-3">
            <label for="titulo" class="form-label">Título</label>
            <input type="text" class="form-control" name="titulo" id="titulo" [(ngModel)]="livro.titulo" required>
        </div>

        <div class="resumo mb-3">
            <label for="resumo" class="form-label">Resumo</label>
            <textarea class="form-control" id="resumo" name="resumo" [(ngModel)]="livro.resumo" required></textarea>
        </div>
        
        <div class="editora mb-3">
            <label for="editora" class="form-label">Editora</label>
            <select id="editora" class="form-select" name="editora" [(ngModel)]="livro.codEditora">
                <option value="0" selected disabled>Selecione uma editora</option>
                <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
            </select>
        </div>

        <div class="autores mb-3">
            <label for="autores" class="form-label">Autores (1 por linha)</label>
            <textarea class="form-control mb-3" id="autores" name="autores" [(ngModel)]="autoresForm" required></textarea>
        </div>

        <button type="submit" class="btn btn-primary">Salvar Dados</button>
    </form>
</main>

// clientes/livros-next/pages/LivroDados.tsx
import type { NextPage } from 'next';
import styles from '../styles/Home.module.css'
import React, { useState } from 'react';
import ControleEditora from '@/classes/controle/ControleEditora';
import Livro from '@/classes/modelo/Livro';
import Router from 'next/router';
import Head from 'next/head';
import { Menu } from '@/componentes/Menu';
import ControleLivros from '@/classes/controle/ControleLivros';


const controleEditora: ControleEditora = new ControleEditora();
const controleLivros: ControleLivros = new ControleLivros();

const LivroDados: NextPage = () => {
    const opcoes = controleEditora.getEditoras().map(editora => ({
        value: editora.codEditora,
        text: editora.nome
    }))

    const [titulo, setTitulo] = useState<string>('');
    const [resumo, setResumo] = useState<string>('');
    const [autores, setAutores] = useState<string>('');
    const [codEditora, setCodEditora] = useState<number>(opcoes[0].value);

    const tratarCombo = (evento: React.ChangeEvent<HTMLSelectElement>) => {
        setCodEditora(Number(evento.target.value));
    };

    const incluir = async (evento: React.FormEvent<HTMLFormElement>) => {
        evento.preventDefault();
        const novoLivro: Livro = {
            codigo: "",
            titulo,
            resumo,
            autores: autores.split('\n'),
            codEditora,
        };
    
        await controleLivros.incluir(novoLivro).then(() => {
            Router.push('LivroLista')
        });
    };

    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Incluir Livro</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Menu />
                <main className="container">
                    <h1>Dados do Livro</h1>
                    <form onSubmit={incluir}>
                        <div className="titulo mb-3">
                            <label htmlFor="titulo" className="form-label">Título</label>
                            <input type="text" className="form-control" id="titulo" value={titulo} onChange={(e) => setTitulo(e.target.value)} required></input>
                        </div>

                        <div className="resumo mb-3">
                            <label htmlFor="resumo" className="form-label">Resumo</label>
                            <textarea className="form-control" id="resumo" value={resumo} onChange={(e) => setResumo(e.target.value)} required></textarea>
                        </div>
                        
                        <div className="editora mb-3">
                            <label htmlFor="editora" className="form-label">Editora</label>
                            <select id="editora" className="form-select" value={codEditora} onChange={tratarCombo}>
                                {opcoes.map(opcao => (
                                    <option key={opcao.value} value={opcao.value}>{opcao.text}</option>
                                ))}
                            </select>
                        </div>
                    
                        <div className="autores mb-3">
                            <label htmlFor="autores" className="form-label">Autores (1 por linha)</label>
                            <textarea className="form-control mb-3" id="autores" value={autores} onChange={(e) => setAutores(e.target.value)} required></textarea>
                        </div>

                        <button type="submit" className="btn btn-primary">Salvar Dados</button>
                    </form>
                </main>
            </div>
        </>
    );
}

export default LivroDados;
